# Generated by Django 4.2.6 on 2024-03-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.CharField(max_length=500)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
