# Generated by Django 4.2.6 on 2024-03-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_rename_messageuser_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
